### ISSUE TITLE
Replacing SDL2 with Winit

### ISSUE THREAD

**Issue by HaronK** [Limit-Theory-Redux/ltheory#138]
The goal of this task is to replace existing SDL code with winit.

I'm going to use Bevy usage of winit as an example.

Screenshot below shows presence of the 'SDL' word in the Rust code:
![LTR-SDL](https://github.com/Limit-Theory-Redux/ltheory/assets/638536/c57f2fd6-dbad-485f-9508-fddc13e18495)

Analysis:
1. **engine**: mostly SDL initialization. Will be replaced with equivalent winit initialization and event loop.
2. **window**: window management stuff. Will be replaced with corresponding winit equivalent.
3. **system**: joystic related code (HAT).
4. **render**: connection to OpenGL. Will be replaced with a **glutin** crate.
5. **input**: code for all input devices and their management. Will be replaced with equivalent winit devices and events.

Refactoring ideas:
1. Main loop will be moved from the Lua code (`Application:run()`) to Rust engine. Lua code will have to provide 3 functions: `AppInit(engine)` - for the script environment initialization, `AppFrame()` - will be called each frame after collecting all winit events, `AppClose()` - will be called on application close. Engine will run infinite event loop in which it collects all events and then calls `AppFrame()`.
2. There will be several types of events: **window** - changes to the window state, **input** - input devices state changes, **drag&drop** - file drag and drop operation, and any other events that winit provides.
3. There is a possibility to support multiple windows and monitors but this won't be included in this refactoring and can be done later if needed.

Engine start and main event loop will look like following:

- Create an engine and main window structure.
- Call `AppInit(engine)` Lua function. Lua script expected to store an engine in some global variable to be used in `AppFrame()` and `AppClose()` calls. Also script can adjust window parameters.
- Create winit window from the window structure.
- Main event loop:
    * Collect all events
    * Call `AppFrame()` and repeat the loop
    * On close call `AppClose()` and exit the loop

Lua script will access **window** and **events** via **engine**: `engine:getWindow():setPosition(x, y)`, `engine:windowEvents():resized()`, `engine:inputEvents():getValue(Key.A)`, etc.

**Comment by IllustrisJack** [comment]
if window is a function it should be getWindow()

**Comment by IllustrisJack** [comment]
Also for the events. What do you think of making them subscription based?

**Comment by HaronK** [comment]
> if window is a function it should be getWindow().

Updated.

> We can also do some lua magic to get it to be the same as before. As the class `Window` won´t be part of FFI anymore we´ll just make it a global.
> 
> ```
> Window = engine:getWindow()
> ```

That was my idea too, so we can do something like this:
```lua
Engine = nil
Window = nil
Events = {}

function AppInit(engine)
    Engine = engine
    Window = engine:getWindow()
    Events.input = engine:inputEvents()
    ...
end

function AppFrame()
    Engine:setPosition(100, 200)
    ...
end
```

**Comment by IllustrisJack** [comment]
> > if window is a function it should be getWindow().
> 
> Updated.
> 
> > We can also do some lua magic to get it to be the same as before. As the class `Window` won´t be part of FFI anymore we´ll just make it a global.
> > ```
> > Window = engine:getWindow()
> > ```
> 
> That was my idea too, so we can do something like this:
> 
> ```lua
> Engine = nil
> Window = nil
> Events = {}
> 
> function AppInit(engine)
>     Engine = engine
>     Window = engine:getWindow()
>     Events.input = engine:inputEvents()
>     ...
> end
> 
> function AppFrame()
>     Engine:setPosition(100, 200)
>     ...
> end
> ```

perfect, that´s how i imagined it :)
