### ISSUE TITLE
Wrong project description:

### ISSUE THREAD

**Issue by larioteo** [Limit-Theory-Redux/ltheory#143]
"This repository continues the game and engine code from the second generation of LT's development, when all work was migrated to C++ and Lua. For the older, C++/LTSL version of Limit Theory, see..."

It was migrated to "C and Lua" not C++, I know his project well, there is nothing about C++ in it.

Please fix you're description.

**Comment by dgavedissian** [comment]
That description was actually written by Josh himself, who also knows the project well 😉  Also, it _was_ written in C++, and was compiled [using a C++ compiler](https://github.com/JoshParnell/libphx/blob/0f804f26aa02f2bb5993c7678357713ea12dd6d8/script/build/Shared.cmake#L69), but only using features from C, and used the C standard library, but a great counter-example of that can be found in the original libphx code here: https://github.com/JoshParnell/libphx/blob/0f804f26aa02f2bb5993c7678357713ea12dd6d8/src/Physics.cpp#L31

That being said, we actually painstakingly ported it to Rust (and fixed a number of memory bugs along the way), so you're absolutely correct that we need to update the description, so I've done that here: https://github.com/Limit-Theory-Redux/ltheory/pull/144/files
