### ISSUE TITLE
Fix line endings for the generated Lua files

### ISSUE THREAD

**Issue by HaronK** [Limit-Theory-Redux/ltheory#145]
Procedural macro uses platform dependent line endings during Lua files generation. This makes a problem for developers committing from different platforms - line endings constantly regenerated and that forces git to create a change.

To resolve this proc macro should use a fixed line endings (LF).

**Comment by dgavedissian** [comment]
I don't think we necessarily need to use the same line endings on all platforms. Instead, we need to configure git to convert line endings automatically. That means on Linux, nothing is needed, but on Windows, we should tell Git to convert CRLF to LF when committing files to the repository. One way to do that is with the `.gitattributes` file

https://www.edwardthomson.com/blog/git_for_windows_line_endings.html

**Comment by HaronK** [comment]
Right, we already have `*.diff text=auto` in `.gitattributes`. We can also add something like `*.lua text=auto` or more generic `* text=auto`.

**Comment by dgavedissian** [comment]
Yep, I think replacing `*.diff` with the fully generic one makes sense.
