### ISSUE TITLE
Investigate `Audio.Create = nil` error in Tests

### ISSUE THREAD

**Issue by IllustrisJack** [Limit-Theory-Redux/ltheory#150]
see https://github.com/Limit-Theory-Redux/ltheory/commit/1fcc49458cc630a10fba0bc08b3845ba656f5ff4

**Comment by dgavedissian** [comment]
I hit this problem as well, and I assumed it's because the `LTheoryRedux` object is the "App" object for `LTheoryRedux`, but when we run a different app like `PhysicsTest`, `LTheoryRedux` will be an empty table? Should the audio not be passed in to GameView at startup ideally?

**Comment by IllustrisJack** [comment]
> I hit this problem as well, and I assumed it's because the `LTheoryRedux` object is the "App" object for `LTheoryRedux`, but when we run a different app like `PhysicsTest`, `LTheoryRedux` will be an empty table? Should the audio not be passed in to GameView at startup ideally?

LTheoryRedux really is just `LTheoryRedux = require('States.Application')` same as `PhysicsTest = require('States.Application')` so it should be the same. That is what bugs me out.
