### ISSUE TITLE
Archetype Value Inconsistency 

### ISSUE THREAD

**Issue by LukeJHarvey** [Limit-Theory-Redux/ltheory#327]
Branch: feat/ecs
Files effected: 
- script/_ECS_WIP_TEMP/Systems/GlobalStorage.lua
- script/Enums/Archetype.lua
- script/_ECS_WIP_TEMP/Entities/Entity.lua
- script/_ECS_WIP_TEMP/Components/Component.lua

Issue: Archetype values stored into GlobalStorage are inconsistently off by 1. This is a known issue for EntityArchetype, but potential issue for ComponentArchetype aswell, given storage is similarly done.

There are no reproduction steps. As this will happen between consecutive runs with no change in code.
Issue could be with storage into GlobalStorage inside the Entity.lua/Component.lua file

Consideration: This issue could be occurring when Enums is added to _G/Namespace, where it is not loading consistently into _g.

**Comment by LukeJHarvey** [comment]
Example
Run 1:
MoonEntity(1ULL)	MoonEntity(5ULL)	PhysicsTransformComponent(3ULL)	PhysicsTransformComponent(7ULL)

Run 2:
AsteroidEntity(1ULL)	AsteroidEntity(5ULL)	PhysicsTransformComponent(3ULL)	PhysicsTransformComponent(7ULL)

When running: cargo r -- RenderingTest

**Comment by IllustrisJack** [comment]
should be fixed in [#903bc20](https://github.com/Limit-Theory-Redux/ltheory/commit/903bc2025f1091e67afe602b63d4b15990ff3c31)
