### ISSUE TITLE
Using real-world galaxies

### ISSUE THREAD

**Issue by atlantis451** [Limit-Theory-Redux/ltheory#330]
- List of nearest galaxies https://en.wikipedia.org/wiki/List_of_nearest_galaxies
https://en.wikipedia.org/wiki/Observable_universe

---

### off-topic
https://exoplanetarchive.ipac.caltech.edu/ NASA confirmed planets

youtube
[Size Comparison of the Universe](https://www.youtube.com/watch?v=134nAVodmp8)
[ABSOLUTE Size Comparison 2023 (FULL) 4K 60FPS 3D](https://www.youtube.com/watch?v=WocfYpjgb8M&t=5576s)

**Comment by IllustrisJack** [comment]
Hello! We only accept feature proposal via discord see https://github.com/Limit-Theory-Redux/ltheory/blob/main/CONTRIBUTING.md so i´ll have to close this issue

**Comment by IllustrisJack** [comment]
> > Hello! We only accept feature proposal via discord see https://github.com/Limit-Theory-Redux/ltheory/blob/main/CONTRIBUTING.md so i´ll have to close this issue
> 
> Sorry. I don't use Discord, and I think it's bad to discuss feature requests on social media

Hey now worries, i´m sorry that it is that way, but we have thorough discussions on discord, which we chose over GH discussions, regarding the project and all implementation discussions. It´s just easier to do community related things in one place. What i can do is post what you wrote here over there so it´s properly tracked.
