### ISSUE TITLE
Star system / object sizes are too limited

### ISSUE THREAD

**Issue by Flatfingers** [Limit-Theory-Redux/ltheory#47]
The extents of star systems, and the sizes of objects in them, currently must be severely constrained to prevent what appear to be rendering problems (planets/atmospheres disappearing, ships "jiggling"). This limitation on star system and object sizes makes it impossible to properly test economic activity (ships require time to move between asteroids and space stations, which affects the rate of economic activity) and prevents the feel of "bigness" important to a space game.

One suggestion for resolving this issue is to support double precision throughout the engine.

An alternative proposal is to move the camera (internally to the engine/renderer) between different local positions then back again. This alternative would be smaller in scope for the engine code than changing to full double precision, but would require some Lua-side changes (replacing Vec3f type assignments with a new type associated with the new camera feature).

Note: Resolving this issue should also resolve Issue 29. (https://github.com/Limit-Theory-Redux/ltheory/issues/29)

**Comment by dgavedissian** [comment]
Closing this in favour of https://github.com/Limit-Theory-Redux/ltheory/issues/221 - I just created that issue without realising this was here.
