### ISSUE TITLE
Support cursor replacement in Lua scripts

### ISSUE THREAD

**Issue by Flatfingers** [Limit-Theory-Redux/ltheory#56]
Although SDL offers a way to replace a cursor based on a provided graphic file, that capability has not yet been implemented in Phoenix and exposed to LuaJIT.

Suggested pseudocode:

```
surface = IMG_Load(filename)
cursor = SDL_CreateColorCursor(surface)
SDL_SetCursor(cursor)
```

**Comment by philip-uk** [comment]
Addressed with https://github.com/Limit-Theory-Redux/ltheory/pull/58

**Comment by philip-uk** [comment]
Initial feature implemented in https://github.com/Limit-Theory-Redux/ltheory/pull/58

**Comment by Flatfingers** [comment]
I _just_ came in here to close this one. :D Works great -- thank you!
