### ISSUE TITLE
Replace the raw C string handling with Rust strings

### ISSUE THREAD

**Issue by HaronK** [Limit-Theory-Redux/ltheory#94]
Replace the raw C string handling with Rust strings - in particular in the Shader parsing code. The end goal would be to delete all the functions beginning with `Str` i.e. `StrDup` in `libphx/src/internal/Memory.rs`

UPD. I'm going to replace all string related code generated by c2rust to rust String/str types.

This can introduce some overhead at places where we send string to C code (i.e. Lua since it works with C-style strings) but it should not be significant (or we will address this later during benchmarking).

**Comment by dgavedissian** [comment]
Something to bare in mind is that we need to be careful that the raw C strings we return through the no_mangle C API has the correct lifetime. For example, we may need to return a string that gets freed the next time the function is called. An example if this is `Device_ToString` in `Device.rs`.

The string ffi helper functions in `libphx/src/internal/ffi.rs` may also come in use.

**Comment by HaronK** [comment]
I just checked [mlua](https://crates.io/crates/mlua) and from the description looks like it supports LuaJIT.
If we can use it, it would solve a lot of issues. But it should be investigated how usable it is.

**Comment by HaronK** [comment]
Yeah, I will concentrate here only on fixing strings.

I was just wondering if we can simplify integration with Lua by using mlua. I didn't look yet deep into the internals of mlua/luajit so don't know how optimal it works. Will take a look at it when I have more time.

**Comment by dgavedissian** [comment]
I'm not sure mlua will be much help unfortunately (but I would encourage further investigation!)

What might be possible is perhaps a way to generate the Rust -> C interop code using a macro? Perhaps given a struct and a method, it generates a C function wrapper for it, converting the types where appropriate using traits or something?

**Comment by HaronK** [comment]
Yes, we can think about some proc macro to automatically generate C/Lua bindings for functions and types (structs, enums, etc).
So it could look something like:
```rust
#[bind_lua]
pub fn Device_ToString(this: &mut Device) -> String {
    ...
}
```
so macro will generate proper extern "C" wrapper.
I have some experience writing proc macros, so I'll think about it later.

**Comment by dgavedissian** [comment]
Sounds great! Currently, a lot of things kind of work already. For example `this: Option<&mut Device>` will be ABI compatible with `Device* this` in C, but it would be super cool if we could receive Rust strings as arguments or return them.

**Comment by HaronK** [comment]
I think things are not so simple because of conversion we have to do: C-string (ASCII) <-> Rust string (UTF-8).

So we convert input C-string parameters to Rust string. We can do this in the wrapper so it will drop Rust string at the end. Input C-string should be managed by Lua.

Output strings should be managed the way you suggested with some modification:
- Rust **String/&'static str** should be converted to **C-string**.
- Original Rust **String** will be destroyed by Rust drop in the wrapper.
- **&'static str** will remain since it's static.
- **C-string** should be destroyed by Lua

I think this is most logical way. There are quite some conversion/copying here but I don't think we can avoid it if we are going to use standard Rust strings.

**Comment by dgavedissian** [comment]
Agreed, I don't think the copying is a big deal, and we can probably do some shortcuts like assume that all C strings are valid UTF-8 strings, like:
```
pub fn PtrAsSlice<'a>(ptr: *const libc::c_char) -> &'a str {
    unsafe { str::from_utf8_unchecked(CStr::from_ptr(ptr).to_bytes()) }
}
```
